"""The household exploration layer; independent of consumable comparisons."""
import html
BASE='https://stusaurus.github.io/pet-cost-jp/'
def esc(x): return html.escape(str(x or ''),quote=True)
def art(name,cls=''):
    return f'<img class="living-art {cls}" src="{BASE}assets/living/{esc(name)}.webp" width="320" height="240" alt="" aria-hidden="true" decoding="async" loading="lazy">'

def profile(species=''):
    parts=[]
    for pet,labels in [('dog',['子犬','成犬','シニア']),('cat',['子猫','成猫','シニア'])]:
        ages=''.join(f'<button type="button" class="portrait-choice" data-profile-age="{age}" aria-pressed="false">{art(pet+"-"+age)}<span>{label}</span></button>' for age,label in zip(['young','adult','senior'],labels))
        sizes=''.join(f'<button type="button" class="portrait-choice" data-profile-size="{size}" aria-pressed="false">{art("size-"+size)}<span>{label}</span></button>' for size,label in [('small','小型'),('medium','中型'),('large','大型')]) if pet=='dog' else ''
        parts.append(f'<div data-profile-species="{pet}" hidden><fieldset><legend>年齢段階（任意）</legend><div class="portrait-grid">{ages}</div><button type="button" class="text-button" data-profile-age-clear>指定しない</button></fieldset>{"<fieldset><legend>現在の体格（任意）</legend><div class=portrait-grid>"+sizes+"</div><button type=button class=text-button data-profile-size-clear>指定しない</button></fieldset>" if sizes else ""}<div class="profile-inputs"><label>現在の体重（kg・任意）<input type="text" inputmode="decimal" data-profile-weight aria-label="{pet}の現在の体重" maxlength="6" placeholder="例：5.2"></label><label>{"犬種" if pet=="dog" else "猫種"}（任意）<input type="text" data-profile-breed aria-label="{pet}の種類" maxlength="40" placeholder="ミックス・分からないもOK"></label></div></div>')
    return f'<details class="pet-profile" data-profile data-species="{species}"><summary><span>うちの子プロフィール <small>任意</small></span><span data-profile-summary>設定しなくても使えます</span></summary><div class="profile-body"><p>年齢・体格は商品表記との照合に。体重や種類から適正商品・給与量を推測しません。</p>{"".join(parts)}<p class="profile-message" data-profile-message role="status"></p><label class="profile-save"><input type="checkbox" data-profile-save>この端末に保存する</label><p class="condition-note">体重・種類はアクセス解析に送信しません。</p><button type="button" class="text-button" data-profile-clear>プロフィールを消す</button></div></details>'

def journey():
    sections=[]
    routes={'dog':[('dog-food','ごはん','いつもの袋は、何日分？','dog-food'),('pet-sheets','トイレ','使っているサイズから','sheets'),('dog-toys','おもちゃ','どんな遊びが好き？','dog-toys')], 'cat':[('cat-food','ごはん','いつもの袋は、何日分？','cat-food'),('cat-litter','猫砂','普段使っている素材から','litter'),('system-toilet-sheets','トイレシート','使っている本体から','system'),('cat-toys','おもちゃ','今日はどう遊ぼう？','cat-toys')]}
    for pet,entries in routes.items():
        links=''.join(f'<a class="living-route" data-living-route="{key}" href="{BASE}categories/{key}/">{art(image)}<span><b>{name}</b><small>{note}</small></span><span aria-hidden="true">→</span></a>' for key,name,note,image in entries)
        sections.append(f'<div data-pet-routes="{pet}" hidden><div class="living-step-heading"><span>02</span><h3>{"犬" if pet=="dog" else "猫"}との暮らし、今日は何を探す？</h3></div><div class="living-route-grid">{links}</div></div>')
    return f'<section class="pet-journey" id="pet-journey" aria-labelledby="pet-journey-heading"><div class="living-step-heading"><span>01</span><div><p class="section-eyebrow">うちの子に合うものから</p><h2 id="pet-journey-heading">うちの子は？</h2></div></div><div class="pet-entry-grid">'+''.join(f'<button type="button" class="pet-entry" data-pet-select="{pet}" aria-pressed="false">{art("entry-"+pet)}<span><b>{label}</b><small>{note}</small></span><span class="pet-entry-mark" aria-hidden="true">→</span></button>' for pet,label,note in [('dog','犬','ごはん・トイレ・遊びの時間'),('cat','猫','ごはん・いつものトイレ・遊び')])+f'</div><p class="living-status" role="status" aria-live="polite" data-living-status>犬・猫を選ぶと、その子の用品が現れます。</p>{"".join(sections)}{profile()}<noscript><p>いつもの用品は、下の直接リンクから比較できます。</p><a href="{BASE}categories/dog-food/">犬のごはん</a> · <a href="{BASE}categories/cat-food/">猫のごはん</a> · <a href="{BASE}categories/dog-toys/">犬のおもちゃ</a> · <a href="{BASE}categories/cat-toys/">猫のおもちゃ</a></noscript></section>'

def catalog_body(key,config,payload,nav,footer,dock):
    species=config['species']; kind=config['kind']; labels={'chew':'噛みたい','chase':'追いかけたい','together':'一緒に遊びたい','puzzle':'頭を使いたい','teaser':'じゃれたい','hide':'もぐる・抱えて遊ぶ'}
    head=f'{nav}<header class="page-intro wrap"><div><p class="home-kicker">{"犬" if species=="dog" else "猫"}との暮らし</p><h1>{esc(config["name"])}</h1><p class="intro-copy">{"いつものごはんを、暮らしの数字に。" if kind=="food" else "うちの子の好きな遊びから。"}</p><a class="text-link" href="{BASE}#pet-journey">犬・猫と用品を選び直す</a></div><div class="category-art">{art(key)}</div></header>'
    if kind=='food':
        content=f'<section class="food-guide"><div class="living-step-heading"><span>01</span><h2>いつものごはん、どのくらい持つ？</h2></div><p>袋の表示と、普段使っている1日量を入力してください。</p><form data-food-calculator novalidate><div class="food-input-grid"><label>袋の内容量（g）<input type="text" inputmode="decimal" data-food-weight aria-label="袋の内容量" placeholder="例：2000"></label><label>袋の価格（税込・円）<input type="text" inputmode="decimal" data-food-price aria-label="袋の価格" placeholder="例：3000"></label><label>1日に使う量（g）<input type="text" inputmode="decimal" data-food-daily aria-label="1日に使うフード量" placeholder="例：120"></label></div><button class="btn" type="submit">暮らしの数字で見る</button></form><div class="food-outcome" data-food-outcome role="status" aria-live="polite">入力すると、日数・1日の費用・30日分・100gと1kg単価に換算します。</div><p class="condition-note">1日量は、ご自身の使用量や商品の給与量表で確認した量を入力してください。体重からの自動推定は行いません。送料は未加算です。</p></section><section class="food-scope"><h2>ごはんは、条件の確認から。</h2><p>犬猫・年齢・食種・総合栄養食の表示を照合してから、同条件で比べる設計です。</p><p>現在、ドッグフード・キャットフードとも取得データとメーカー表記を照合中です。確認前の商品や価格順位は掲載していません。</p><p>療法食・疾病やアレルギーへの対応はこの比較の対象外です。獣医師から指示がある場合は、その指示に沿って商品を確認してください。</p></section>'
    else:
        keys=['chew','chase','together','puzzle'] if species=='dog' else ['teaser','chase','hide','puzzle']
        buttons=''.join(f'<button type="button" class="play-choice" data-play-select="{k}" aria-pressed="false">{art("play-"+k)}<span>{labels[k]}</span></button>' for k in keys)
        cards=[]
        for i,item in enumerate(payload.get('items',[]),1):
            evidence=' · '.join(x['quote'] for x in item['evidence'])
            cards.append(f'<article class="toy-candidate" data-toy-candidate data-play="{item["play"]}" data-age="{item["age"]}" data-size="{item["size"]}" hidden><img src="{esc(item.get("image"))}" alt="{esc(item["name"])}" width="92" height="92" loading="lazy"><div><p class="candidate-reason">候補になった理由：{esc(evidence)}</p><h3>{esc(item["name"])}</h3><p>{esc(item["dimensions"])} · {esc(item["shop"])}</p><p>商品価格 ¥{item["price"]:,} · {"送料込み" if str(item.get("postage_flag"))=="0" else "送料は楽天で確認"}</p><a class="btn secondary" data-affiliate-link data-category-id="{key}" data-item-id="{item["product_id"]}" data-item-name="{esc(item["name"])}" data-position="{i}" data-conversion-source="play_discovery" href="{esc(item["url"])}" target="_blank" rel="nofollow sponsored noopener">楽天でサイズ・仕様を確認</a></div></article>')
        content=f'<section class="play-discovery"><div class="living-step-heading"><span>01</span><h2>どんな遊びが好き？</h2></div><p>遊び方を選ぶと、商品表記を確認できた候補が現れます。</p><div class="play-choice-grid">{buttons}</div><p class="living-status" role="status" aria-live="polite" data-toy-status>遊び方を選んでください。価格・品質のランキングではありません。</p><p class="toy-empty" data-toy-empty hidden>この条件で、商品情報を確認できた候補はありません。プロフィールの年齢・体格を指定している場合、表記がない商品は表示しません。</p><div class="toy-candidates">{"".join(cards)}</div><p class="condition-note">候補は商品名順。適合や壊れにくさを保証するものではありません。紐・羽・小部品の誤飲、破損、対象サイズを確認し、飼い主の見守りのもとで使用してください。</p></section>'
    return f'{head}<main id="main" class="main wrap" data-discovery-id="{key}" data-discovery-species="{species}">{profile(species)}{content}<section class="discovery-return"><h2>いつものトイレ用品も、うちの条件で。</h2><a class="text-link" href="{BASE}categories/{"pet-sheets" if species=="dog" else "cat-litter"}/">{"シーツのサイズ" if species=="dog" else "猫砂の素材"}から比較する →</a></section></main>{footer}{dock}'
